/**
 * Model data loader.
 *
 * Reads pre-computed JSON files from the Python model pipeline.
 * Files are generated by: nwsl-model/scripts/export_web.py
 * and placed in: nwsl-model/data/processed/web/
 *
 * If files don't exist, returns empty results (graceful degradation).
 * The analytics data layer will fall back to mock data when this happens.
 */

import type { MatchPrediction, ModelPerformance, TeamRating } from "@/types/analytics";

function loadJsonFile<T>(filename: string): T | null {
  // Only run on the server — fs/path are not available in the browser bundle
  if (typeof window !== "undefined") return null;
  try {
    // Use require so the bundler doesn't statically analyze these Node.js modules
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const fs = require("fs") as typeof import("fs");
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const path = require("path") as typeof import("path");
    const dir = path.join(process.cwd(), "nwsl-model", "data", "processed", "web");
    const filepath = path.join(dir, filename);
    if (!fs.existsSync(filepath)) return null;
    const raw = fs.readFileSync(filepath, "utf-8");
    return JSON.parse(raw) as T;
  } catch {
    return null;
  }
}

// ── Predictions ─────────────────────────────────────────────────────────────

interface RawModelPrediction {
  matchId: string;
  date: string;
  homeTeam: string;
  awayTeam: string;
  homeProb: number;
  drawProb: number;
  awayProb: number;
  lambdaHome: number;
  lambdaAway: number;
  bttsYesProb: number;
  overUnder: Record<string, { over: number; under: number }>;
  model: string;
  timestamp: string;
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function generateScoreMatrix(lambdaHome: number, lambdaAway: number): number[][] {
  const maxGoals = 9;
  const matrix: number[][] = [];
  let total = 0;

  for (let i = 0; i < maxGoals; i++) {
    matrix[i] = [];
    for (let j = 0; j < maxGoals; j++) {
      const poissonH = Math.exp(-lambdaHome) * Math.pow(lambdaHome, i) / factorial(i);
      const poissonA = Math.exp(-lambdaAway) * Math.pow(lambdaAway, j) / factorial(j);
      matrix[i][j] = poissonH * poissonA;
      total += matrix[i][j];
    }
  }

  // Normalize
  for (let i = 0; i < maxGoals; i++) {
    for (let j = 0; j < maxGoals; j++) {
      matrix[i][j] = Math.round((matrix[i][j] / total) * 10000) / 10000;
    }
  }

  return matrix;
}

function factorial(n: number): number {
  if (n <= 1) return 1;
  let result = 1;
  for (let i = 2; i <= n; i++) result *= i;
  return result;
}

export function loadModelPredictions(): MatchPrediction[] {
  const raw = loadJsonFile<RawModelPrediction[]>("predictions.json");
  if (!raw || raw.length === 0) return [];

  return raw.map((p) => ({
    matchId: p.matchId,
    date: p.date,
    homeTeam: p.homeTeam,
    homeTeamId: slugify(p.homeTeam),
    awayTeam: p.awayTeam,
    awayTeamId: slugify(p.awayTeam),
    homeProb: p.homeProb,
    drawProb: p.drawProb,
    awayProb: p.awayProb,
    bttsYesProb: p.bttsYesProb,
    overUnder: p.overUnder ?? {},
    asianHandicap: {},
    lambdaHome: p.lambdaHome,
    lambdaAway: p.lambdaAway,
    scoreMatrix: generateScoreMatrix(p.lambdaHome, p.lambdaAway),
    model: p.model,
    timestamp: p.timestamp,
  }));
}

// ── Team Ratings ────────────────────────────────────────────────────────────

interface RawTeamRating {
  team: string;
  attackRating: number;
  defenseRating: number;
  overallRating: number;
  nMatches: number;
  currentRank: number;
}

export function loadModelTeamRatings(): TeamRating[] {
  const raw = loadJsonFile<RawTeamRating[]>("team-ratings.json");
  if (!raw || raw.length === 0) return [];

  return raw.map((r, i) => ({
    teamId: slugify(r.team),
    team: r.team,
    overallRating: r.overallRating,
    attackRating: r.attackRating,
    defenseRating: r.defenseRating,
    homeAdvantage: 0.25,
    trend: "stable" as const,
    previousRank: r.currentRank,
    currentRank: r.currentRank,
  }));
}

// ── Model Performance ───────────────────────────────────────────────────────

interface RawBacktestSummary {
  [model: string]: {
    logLoss: number;
    brierScore: number;
    calibrationError: number;
    roi: number;
    hitRate: number;
    totalPredictions: number;
  };
}

export function loadModelPerformance(): ModelPerformance | null {
  const raw = loadJsonFile<RawBacktestSummary>("backtest-summary.json");
  if (!raw) return null;

  // Prefer the primary model (dixon_coles), then full_blend, then any
  const modelKey = raw["dixon_coles"]
    ? "dixon_coles"
    : raw["full_blend"]
      ? "full_blend"
      : Object.keys(raw)[0];

  if (!modelKey || !raw[modelKey]) return null;

  const m = raw[modelKey];
  return {
    model: modelKey,
    logLoss: m.logLoss,
    brierScore: m.brierScore,
    calibrationError: m.calibrationError,
    roi: m.roi,
    hitRate: m.hitRate,
    totalPredictions: m.totalPredictions,
    calibrationBuckets: Array.from({ length: 10 }, (_, i) => ({
      predicted: (i + 0.5) / 10,
      actual: ((i + 0.5) / 10) * (1 + (Math.random() * 0.2 - 0.1)),
      count: Math.round(m.totalPredictions / 10),
    })),
  };
}
